// Anchor parity with github-slugger — the slugger Docusaurus and GitHub
// actually render with. Pancake's generated anchor must equal the
// framework's rendered id, or deep links land wrong. The battery in
// fixtures/github-slugger-vectors.json was generated by the real library;
// when a local copy of github-slugger is present (docs-site/node_modules)
// the test additionally runs the live library to catch battery drift.
//
// Two documented divergences, both deliberate:
// - multi-space heading runs: cleanHeading collapses whitespace for
//   display, so "Why is  this   spaced" slugs without the doubled dashes
//   github-slugger emits; multi-space headings are effectively nonexistent
//   in real docs.
// - JSX component tags in headings: MDX strips <Component /> before
//   slugging (it would not render as text), so its slug drops the word.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { check, section } from './harness.mjs';
import { pipeline } from './markdown.test.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const CPS = path.resolve(here, '..', '..', 'create-pancake-search', 'src', 'ingest.mjs');
const { extractMarkdown } = await import(CPS);

const KNOWN_DIVERGENCES = new Map([
  ['Why is  this   spaced', 'why-is-this-spaced'],
  ['The <Component /> story', 'the-story'],
]);

function pancakeSlugs(headings) {
  // Run the battery through the real extraction path (one doc, one
  // slugger instance, so duplicate handling is exercised too).
  const body = headings.map((heading) => `## ${heading}\n\nfiller\n`).join('\n');
  const { sections } = extractMarkdown(`# Battery\n\n${body}`);
  return sections.filter((s) => s.headingPath.length).map((s) => s.anchor);
}

section('anchors: github-slugger parity battery');
{
  const vectors = JSON.parse(fs.readFileSync(path.join(here, 'fixtures', 'github-slugger-vectors.json'), 'utf8'));
  const slugs = pancakeSlugs(vectors.map((v) => v.heading));
  let mismatches = [];
  vectors.forEach((v, i) => {
    const expected = KNOWN_DIVERGENCES.get(v.heading) ?? v.slug;
    if (slugs[i] !== expected) mismatches.push(`${JSON.stringify(v.heading)}: ${slugs[i]} != ${expected}`);
  });
  check(`all ${vectors.length} battery slugs match github-slugger (2 documented divergences)`,
    mismatches.length === 0, mismatches.join('; '));

  // Live parity when the real library is installed locally.
  let GithubSlugger = null;
  try {
    GithubSlugger = createRequire(import.meta.url)(path.resolve(here, '..', '..', 'docs-site', 'node_modules', 'github-slugger'));
  } catch { /* not installed; the recorded vectors above stand alone */ }
  if (GithubSlugger) {
    const live = new (GithubSlugger.default || GithubSlugger)();
    const drift = vectors.filter((v) => live.slug(v.heading) !== v.slug);
    check('recorded vectors match the live github-slugger', drift.length === 0,
      drift.map((v) => v.heading).join('; '));
  } else {
    console.log('  (live github-slugger not installed; recorded vectors stand alone)');
  }
}

section('anchors: end-to-end href for the canonical example');
{
  // The shape this suite exists to protect:
  //   docs/auth.md, Authentication > API keys > Rotating keys
  //   -> headingPath ["API keys","Rotating keys"], #rotating-keys,
  //      /docs/auth#rotating-keys
  const { chunks } = pipeline('auth.md');
  const target = chunks.find((c) => c.anchor === 'rotating-keys');
  check('headingPath', JSON.stringify(target?.headingPath) === '["API keys","Rotating keys"]', JSON.stringify(target?.headingPath));
  check('anchor', target?.anchor === 'rotating-keys');
  check('href', target?.href === '/docs/auth#rotating-keys', target?.href);
  check('chunk text is the section body', /issuing a second key first/.test(target?.text || ''));
}
