var P=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var a=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,t=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,v=(c,d)=>{throw d;};"undefined"!=typeof __filename&&(_scriptName=__filename);var w="",x,y;
if(t){var fs=require("node:fs");w=__dirname+"/";y=c=>{c=z(c)?new URL(c):c;return fs.readFileSync(c)};x=async c=>{c=z(c)?new URL(c):c;return fs.readFileSync(c,void 0)};process.argv.slice(2);v=(c,d)=>{process.exitCode=c;throw d;}}else if(aa||ba){try{w=(new URL(".",_scriptName)).href}catch{}x=async c=>{c=await fetch(c,{credentials:"same-origin"});if(c.ok)return c.arrayBuffer();throw Error(c.status+" : "+c.url);}}
var A=console.log.bind(console),B=console.error.bind(console),C,D=!1,E,z=c=>c.startsWith("file://"),G,H,I,J,K,L=!1;function M(){var c=N.buffer;I=new Int8Array(c);new Int16Array(c);a.HEAPU8=J=new Uint8Array(c);new Uint16Array(c);a.HEAP32=new Int32Array(c);a.HEAPU32=K=new Uint32Array(c);a.HEAPF32=new Float32Array(c);new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c)}
function O(c){a.onAbort?.(c);c="Aborted("+c+")";B(c);D=!0;c=new WebAssembly.RuntimeError(c+". Build with -sASSERTIONS for more info.");H?.(c);throw c;}var P;async function ca(c){if(!C)try{var d=await x(c);return new Uint8Array(d)}catch{}if(c==P&&C)c=new Uint8Array(C);else if(y)c=y(c);else throw"both async and sync fetching of the wasm failed";return c}
async function da(c,d){try{var b=await ca(c);return await WebAssembly.instantiate(b,d)}catch(e){B(`failed to asynchronously prepare wasm: ${e}`),O(e)}}async function ea(c){var d=P;if(!C&&!t)try{var b=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,c)}catch(e){B(`wasm streaming compile failed: ${e}`),B("falling back to ArrayBuffer instantiation")}return da(d,c)}
class Q{name="ExitStatus";constructor(c){this.message=`Program terminated with exit(${c})`;this.status=c}}
var R=c=>{for(;0<c.length;)c.shift()(a)},S=[],T=[],fa=()=>{var c=a.preRun.shift();T.push(c)},U=!0,V=0,W={},X=c=>{E=c;U||0<V||(a.onExit?.(c),D=!0);v(c,new Q(c))},ha=c=>{if(!D)try{c()}catch(d){d instanceof Q||"unwind"==d||v(1,d)}finally{if(!(U||0<V))try{E=c=E,X(c)}catch(d){d instanceof Q||"unwind"==d||v(1,d)}}},ia=[null,[],[]],ja=globalThis.TextDecoder&&new TextDecoder,ka=(c,d=0)=>{var b=d;for(var e=b+void 0;c[b]&&!(b>=e);)++b;if(16<b-d&&c.buffer&&ja)return ja.decode(c.subarray(d,b));for(e="";d<b;){var f=
c[d++];if(f&128){var k=c[d++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var q=c[d++]&63;f=224==(f&240)?(f&15)<<12|k<<6|q:(f&7)<<18|k<<12|q<<6|c[d++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},na=(c,d,b,e)=>{var f={string:h=>{var m=0;if(null!==h&&void 0!==h&&0!==h){for(var g=m=0;g<h.length;++g){var l=h.charCodeAt(g);127>=l?m++:2047>=l?m+=2:55296<=l&&57343>=l?(m+=4,++g):m+=3}var r=m+1;g=
m=Y(r);l=J;if(0<r){r=g+r-1;for(var F=0;F<h.length;++F){var n=h.codePointAt(F);if(127>=n){if(g>=r)break;l[g++]=n}else if(2047>=n){if(g+1>=r)break;l[g++]=192|n>>6;l[g++]=128|n&63}else if(65535>=n){if(g+2>=r)break;l[g++]=224|n>>12;l[g++]=128|n>>6&63;l[g++]=128|n&63}else{if(g+3>=r)break;l[g++]=240|n>>18;l[g++]=128|n>>12&63;l[g++]=128|n>>6&63;l[g++]=128|n&63;F++}}l[g]=0}}return m},array:h=>{var m=Y(h.length);I.set(h,m);return m}};c=a["_"+c];var k=[],q=0;if(e)for(var p=0;p<e.length;p++){var u=f[b[p]];u?
(0===q&&(q=la()),k[p]=u(e[p])):k[p]=e[p]}b=c(...k);return b=function(h){0!==q&&ma(q);return"string"===d?h?ka(J,h):"":"boolean"===d?!!h:h}(b)};a.noExitRuntime&&(U=a.noExitRuntime);a.print&&(A=a.print);a.printErr&&(B=a.printErr);a.wasmBinary&&(C=a.wasmBinary);if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.shift()();a.ccall=na;
a.cwrap=(c,d,b,e)=>{var f=!b||b.every(k=>"number"===k||"boolean"===k);return"string"!==d&&f&&!e?a["_"+c]:(...k)=>na(c,d,b,k,e)};a.writeAsciiToMemory=(c,d,b)=>{for(var e=0;e<c.length;++e)I[d++]=c.charCodeAt(e);b||(I[d]=0)};
var oa,ma,Y,la,N,pa={d:()=>O(""),b:()=>{U=!1;V=0},c:(c,d)=>{W[c]&&(clearTimeout(W[c].id),delete W[c]);if(!d)return 0;var b=setTimeout(()=>{delete W[c];ha(()=>oa(c,performance.now()))},d);W[c]={id:b,i:d};return 0},e:c=>{var d=J.length;c>>>=0;if(2147483648<c)return!1;for(var b=1;4>=b;b*=2){var e=d*(1+.2/b);e=Math.min(e,c+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(c,e)/65536))-N.buffer.byteLength+65535)/65536|0;try{N.grow(e);M();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},
f:(c,d,b,e)=>{for(var f=0,k=0;k<b;k++){var q=K[d>>2],p=K[d+4>>2];d+=8;for(var u=0;u<p;u++){var h=c,m=J[q+u],g=ia[h];0===m||10===m?((1===h?A:B)(ka(g)),g.length=0):g.push(m)}f+=p}K[e>>2]=f;return 0},a:X},Z;
Z=await (async function(){function c(b){b=Z=b.exports;a._pi=b.Ha;a._pa=b.j;a._bulk_insert=b.k;a._pq=b.l;a._export_index=b.La;a._import_index=b.n;a._pc=b.o;a._pm=b.p;a._pd=b.Ja;a._p_ghost_count=b.r;a._p_ghost_ratio=b.s;a._p_compact=b.t;a._dct_init=b.u;a._dct_project=b.v;a._dct_project_batch=b.w;a._dct_update=b.x;a._dct_a=b.y;a._dct_q=b.z;a._dct_bulk_insert=b.A;a._dct_c=b.B;a._dct_m=b.C;a._dct_d=b.D;a._dct_ghost_count=b.E;a._dct_ghost_ratio=b.F;a._dct_compact=b.G;a._dct_export_index=b.H;a._dct_import_index=
b.I;a._dct_source_dim=b.J;a._dct_target_dim=b.K;a._si_init=b.L;a._si_add=b.M;a._si_query=b.N;a._si_delete=b.O;a._si_count=b.P;a._si_memory=b.Q;a._si_segment_count=b.R;a._si_ghost_count=b.S;a._si_ghost_ratio=b.T;a._si_compact=b.U;a._si_set_budget=b.V;a._si128_init=b.W;a._si128_add=b.X;a._si128_query=b.Y;a._si128_delete=b.Z;a._si128_count=b._;a._si128_memory=b.$;a._si128_segment_count=b.aa;a._si128_ghost_count=b.ba;a._si128_compact=b.ca;a._si128_set_budget=b.da;a._si128_get_vector_segment=b.ea;a._si128_get_query_segments=
b.fa;a._p128_init=b.ga;a._p128_add=b.ha;a._p128_query=b.ia;a._p128_count=b.ja;a._p128_memory=b.ka;a._p128f_init=b.la;a._p128f_add=b.ma;a._p128f_query=b.na;a._p128f_count=b.oa;a._p128f_memory=b.j;a._p128f_get_neighbors=b.qa;a._p384f_init=b.ra;a._p384f_add=b.sa;a._p384f_query=b.ta;a._p384f_count=b.ua;a._p384f_memory=b.va;a._p384f_get_neighbors=b.wa;a._p256f_init=b.xa;a._p256f_add=b.ya;a._p256f_query=b.za;a._p256f_count=b.Aa;a._p256f_memory=b.Ba;a._naive_init=b.Ca;a._naive_add=b.Da;a._naive_query=b.Ea;
a._naive_count=b.Fa;a._naive_get_neighbors=b.Ga;a._i=b.Ha;a._a=b.Ia;a._q=b.Ja;a._c=b.Ka;a._m=b.La;a._d=b.Ma;a._ghost_count=b.Na;a._ghost_ratio=b.Oa;a._compact=b.Pa;a._emsc_malloc=b.Qa;a._emsc_free=b.Ra;a._float_init=b.Sa;a._float_add=b.Ta;a._float_query=b.Ua;a._float_count=b.Va;a._float_memory=b.Wa;a._emb_init=b.Xa;a._emb_encode=b.Ya;a._emb_encode_batch=b.Za;a._emb_dimension=b._a;a._emb_free=b.$a;a._emb_add=b.ab;a._emb_search=b.bb;a._i8_init=b.cb;a._i8_add=b.db;a._i8_query=b.eb;a._i8_count=b.fb;a._i8_memory=
b.gb;a._i8_delete=b.hb;a._i8_ghost_count=b.ib;a._i8_ghost_ratio=b.jb;a._i8_compact=b.kb;a._i8_export_index=b.lb;a._i8_import_index=b.mb;a._shutdown_all=b.nb;oa=b.ob;ma=b.pb;Y=b.qb;la=b.rb;N=b.g;M();return Z}var d={a:pa};if(a.instantiateWasm)return new Promise(b=>{a.instantiateWasm(d,(e,f)=>{b(c(e,f))})});P??=a.locateFile?a.locateFile("engine.wasm",w):w+"engine.wasm";return c((await ea(d)).instance)}());
(function(){function c(){a.calledRun=!0;if(!D){L=!0;Z.h();G?.(a);a.onRuntimeInitialized?.();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();S.push(d)}R(S)}}if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)fa();R(T);a.setStatus?(a.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>a.setStatus(""),1);c()},1)):c()})();L?moduleRtn=a:moduleRtn=new Promise((c,d)=>{G=c;H=d});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=P;module.exports.default=P}else if(typeof define==="function"&&define["amd"])define([],()=>P);
